# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-16 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.University')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Student')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
