# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='num_university',
        ),
        migrations.RemoveField(
            model_name='report',
            name='student',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
