# Generated by Django 2.2.5 on 2019-09-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20190918_0555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={},
        ),
    ]
